# Generated by Django 5.0.8 on 2024-08-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
